// ranking.ts golden tests, compared against the frozen Python ranking.py (ground truth =
// fixtures/expected_ranking.json, generated by test/gen_ranking_gt.py). The inputs (symbols/refs/opts)
// are defined by the Python generator and TypeScript is fed the same inputs, so the two sides' case
// definitions cannot drift apart. Floating-point PageRank uses toBeCloseTo: IEEE 754 agrees across
// the two languages, and the tolerance covers the last digit.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  wellNamed,
  symbolQualityMult,
  buildPersonalization,
  computePagerank,
  rankSymbols,
  type RankSymbol,
  type RankRef,
} from "../src/ranking.js";

const here = dirname(fileURLToPath(import.meta.url));

interface RankingGroundTruth {
  wellnamed: Array<{ name: string; result: boolean }>;
  quality: Array<{ name: string; defines: number; mult: number }>;
  personalization: Array<{
    symbols: RankSymbol[];
    focus_symbols: string[] | null;
    focus_files: string[] | null;
    result: Record<string, number> | null;
  }>;
  pagerank: Array<{
    label: string;
    symbols: RankSymbol[];
    refs: RankRef[];
    opts: { focus_symbols?: string[]; focus_files?: string[] };
    ranked_names: string[];
    scores: Record<string, number>;
  }>;
}
const gt = JSON.parse(
  readFileSync(join(here, "fixtures", "expected_ranking.json"), "utf-8"),
) as RankingGroundTruth;

describe("ranking golden tests: wellNamed against the Python version", () => {
  for (const c of gt.wellnamed) {
    it(`wellNamed(${c.name}) === ${c.result}`, () => {
      expect(wellNamed(c.name)).toBe(c.result);
    });
  }
});

describe("ranking golden tests: symbolQualityMult against the Python version", () => {
  for (const c of gt.quality) {
    it(`mult(${c.name}, defines=${c.defines})`, () => {
      expect(symbolQualityMult(c.name, c.defines)).toBeCloseTo(c.mult, 12);
    });
  }
});

describe("ranking golden tests: buildPersonalization against the Python version", () => {
  gt.personalization.forEach((c, i) => {
    it(`personalization #${i} (focus_symbols=${JSON.stringify(c.focus_symbols)})`, () => {
      const p = buildPersonalization(c.symbols, c.focus_symbols, c.focus_files);
      if (c.result === null) {
        expect(p).toBeNull();
        return;
      }
      expect(p).not.toBeNull();
      const obj = Object.fromEntries(p!);
      // the same set of symbol_id keys, then every weight value (the symbol_id string format is
      // identical in both languages)
      expect(new Set(Object.keys(obj))).toEqual(new Set(Object.keys(c.result)));
      for (const [k, v] of Object.entries(c.result)) {
        expect(obj[k]).toBeCloseTo(v, 12);
      }
    });
  });
});

describe("ranking golden tests: computePagerank + rankSymbols against the Python version", () => {
  for (const c of gt.pagerank) {
    const focusSymbols = c.opts.focus_symbols ?? null;
    const focusFiles = c.opts.focus_files ?? null;

    it(`pagerank "${c.label}": rankSymbols ordering matches Python`, () => {
      const ranked = rankSymbols(c.symbols, c.refs, { focusSymbols, focusFiles });
      expect(ranked.map((s) => s.name)).toEqual(c.ranked_names);
    });

    it(`pagerank "${c.label}": computePagerank scores match Python`, () => {
      const pers = buildPersonalization(c.symbols, focusSymbols, focusFiles);
      const scores = computePagerank(c.symbols, c.refs, { personalization: pers });
      // same node count
      expect(scores.size).toBe(Object.keys(c.scores).length);
      // then each symbol_id's score, to 9 decimal places
      for (const [sid, sc] of Object.entries(c.scores)) {
        const got = scores.get(sid);
        expect(got, `score for ${sid}`).toBeDefined();
        expect(got!).toBeCloseTo(sc, 9);
      }
    });
  }
});
