// symbols.ts golden tests, compared against the symbol output of the frozen Python version v0.15.0
// (the ground truth).
//
// The ground truth is generated by scratchpad/gen_ground_truth.py, which runs the Python version over
// every file under fixtures/samples/ and writes fixtures/expected/<name>.json. These tests run the
// TypeScript extractSymbols over the same sample files and deep-equal the results. Agreement proves
// symbol parity between the TypeScript and Python versions, which is the P1 pass criterion in §4 of
// the blueprint.
//
// The samples cover every kind across 16 languages plus the important special cases: Python
// module-variable assignment and nested function scope, JS destructuring being skipped, TS
// interface/type/abstract, Go type_spec, Rust impl scope, C++ qualified declarators
// (Widget::doIt→doIt), Kotlin name_rules, Ruby keyword tokens (module/class/singleton_method),
// C# constructor/property/record, and the Swift enum→class limitation.
import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { extractSymbols, type SymbolDef } from "../src/symbols.js";

const here = dirname(fileURLToPath(import.meta.url));
const samplesDir = join(here, "fixtures", "samples");
const expectedDir = join(here, "fixtures", "expected");

const sampleFiles = readdirSync(samplesDir).sort();

describe("symbols golden tests (against the Python v0.15.0 ground truth)", () => {
  it("all 16 language samples are present, so none is silently skipped", () => {
    expect(sampleFiles.length).toBe(16);
  });

  for (const name of sampleFiles) {
    it(`${name} symbols match the Python version`, { timeout: 30000 }, async () => {
      const got = await extractSymbols(join(samplesDir, name));
      const expected = JSON.parse(
        readFileSync(join(expectedDir, `${name}.json`), "utf-8"),
      ) as SymbolDef[];
      expect(got).toEqual(expected);
    });
  }
});
